version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/x7l4m0u2
  build:
    commands:
      - export DB_NAME=$DB_NAME
      - export DB_USER=$DB_USER
      - export DB_PASS=$DB_PASS
      - export DB_HOST=$DB_HOST
      - export DB_PORT=$DB_PORT 
      - IMAGE_TAG=$CODEBUILD_BUILD_NUMBER
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t mongo .
      - docker tag mongo:latest public.ecr.aws/x7l4m0u2/mongo:latest
      - docker push public.ecr.aws/x7l4m0u2/mongo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - echo deploy started
      - ls
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
